name: Check formatting of Rust code
on:
  workflow_call:
jobs:
  check-fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Check formatting
        run: cargo fmt --all --check
