name: Build documentation using Sphinx
on:
  workflow_call:
    inputs:
      source:
        description: 'Sphinx source directory'
        type: string
        required: false
        default: 'docs'
jobs:
  build-docs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: target/wheels
      - name: Install package and Sphinx
        run: python -m pip install --find-links=target/wheels . sphinx
      - name: Build documentation
        run: python -m sphinx ${{ inputs.source }} target/sphinx
      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: target/sphinx
